Repository Tephida/Tephida, pull requests merged in 2022-04, with the labels that each got.

#63 Develop
  composer.json
Labels: dependencies

#64 Develop
  .github/workflows/auto_release.yml
Labels: type:build

#66 Update action Release Drafter
  .github/release-drafter.yml
Labels: type:build

#67 Develop
  composer.json
  system/functions.php
  tests/classes/CacheTest.php
Labels: dependencies, type:helper, type:tests

#68 Removed bugs module
  system/init.php
  system/modules/Bugs.php
  templates/Mixchat/bugs/add.blade.php
  templates/Mixchat/bugs/main.blade.php
  templates/Mixchat/bugs/record.blade.php
  templates/Mixchat/bugs/record_one.blade.php
  templates/Mixchat/bugs/view.blade.php
  templates/Mixchat/bugs/view_page.blade.php
Labels: type:modules, type:templates

#69 Moved styles
  css/dist.css
  css/style.css
  dist/output.css
  package.json
  system/inc/tpl/main.tpl
  templates/Mixchat/main.tpl
  templates/Mixchat/main/main.blade.php
Labels: type:admin, type:templates

#70 Develop
  css/im_chat.css
  images/bgmob.jpg
  images/chrome.gif
  images/covers.png
  images/elka.gif
  images/firefox.gif
  images/georg_lent.png
  images/georg_small.png
  images/logo_new.png
  images/map1.png
  images/map2.png
  images/newlogo.png
  images/opera.gif
  images/shatmp.png
  images/techlogo.png
Labels: type:templates

#71 Develop
  images/icons/be.gif
  images/icons/kubok.png
  images/icons/kubok2.png
  images/icons/kubok3.png
  images/icons/ru.gif
  images/icons/ua.gif
  images/icons/usa.gif
Labels: type:templates

#72 update cache
  system/classes/Cache.php
  system/classes/Dialog.php
  system/classes/Friends.php
  system/classes/TpLSite.php
  system/classes/View.php
  system/functions.php
  system/inc/modules/city.php
  system/inc/modules/country.php
  system/inc/modules/massaction.php
  system/inc/modules/musics.php
  system/inc/modules/mysettings.php
  system/inc/modules/report.php
  system/inc/modules/videos.php
  system/modules/Profile.php
  system/modules/Register.php
  system/modules/albums.php
  system/modules/audio.php
  system/modules/del_my_page.php
  system/modules/distinguish.php
  system/modules/doc.php
  system/modules/editprofile.php
  system/modules/friends.php
  system/modules/gifts.php
  system/modules/groups.php
  system/modules/groups_forum.php
  system/modules/im.php
  system/modules/news.php
  system/modules/notes.php
  system/modules/photo.php
  system/modules/public_videos.php
  system/modules/rating.php
  system/modules/repost.php
  system/modules/settings.php
  system/modules/status.php
  system/modules/subscriptions.php
  system/modules/updates.php
  system/modules/videos.php
  system/modules/votes.php
  system/modules/wall.php
Labels: type:helper, type:classes, type:modules, type:admin

#73 strict type
  system/inc/modules/ban.php
  system/inc/modules/city.php
  system/inc/modules/country.php
  system/inc/modules/groups.php
  system/inc/modules/massaction.php
  system/inc/modules/musics.php
  system/inc/modules/mysettings.php
  system/inc/modules/report.php
  system/inc/modules/reviews.php
  system/inc/modules/static.php
  system/inc/modules/users.php
  system/inc/modules/videos.php
Labels: type:admin

#74 Update actions
  .github/workflows/test.yaml
  phpunit.xml.dist
  system/inc/modules/massaction.php
Labels: type:admin, type:tests, type:build

#76 Develop
  .coveralls.yml
Labels: type:build

#78 Develop
  composer.json
Labels: dependencies

#86 fix
  composer.json
  install.php
  system/classes/Module.php
  system/data/mysql_tables.php
  system/functions.php
  system/init.php
  system/login.php
  system/modules/Support.php
  system/modules/supportd.php
  templates/Mixchat/support/support.blade.php
Labels: type:helper, type:classes, type:modules, type:templates

#87 Fix
  composer.json
  install.php
  system/classes/Module.php
  system/data/mysql_tables.php
  system/functions.php
  system/init.php
  system/login.php
  system/modules/Communities.php
  system/modules/Support.php
  system/modules/supportd.php
  templates/Mixchat/support/support.blade.php
Labels: type:helper, type:classes, type:modules, type:templates, fix

#89 Create SECURITY.md
  SECURITY.md
Labels: patch

#90 Actions update
  .github/assignee.config.yml
  .github/dependabot.yml
  .github/workflows/ci.yml
Labels: type:build, approved

#96 release drafter update and remove mod file
  .github/labeler.config.yml
  .github/release-drafter.yml
  system/mod.php
Labels: type:build

#100 Update README.md
  README.md
Labels: theme:docs, patch

#101 Develop
  CONTRIBUTING.md
  README.md
  composer.json
  index.php
  install.php
  system/Mozg.php
  system/exception/ErrorException.php
  system/functions.php
  system/inc/tpl/main.tpl
  system/modules/News.php
  templates/Mixchat/install/install.blade.php
  templates/Mixchat/install/installed.blade.php
  templates/Mixchat/install/main.blade.php
  templates/Mixchat/install/settings.blade.php
  templates/Mixchat/install/system.blade.php
  tests/classes/CacheTest.php
Labels: dependencies, type:helper, type:major, type:modules, type:admin, type:tests, type:templates, theme:docs

#102 Develop
  .github/labeler.config.yml
  .github/release-drafter.yml
  CONTRIBUTING.md
  README.md
  composer.json
  index.php
  install.php
  system/Mozg.php
  system/exception/ErrorException.php
  system/functions.php
  system/inc/tpl/main.tpl
  system/mod.php
  system/modules/News.php
  templates/Mixchat/install/install.blade.php
  templates/Mixchat/install/installed.blade.php
  templates/Mixchat/install/main.blade.php
  templates/Mixchat/install/settings.blade.php
  templates/Mixchat/install/system.blade.php
  tests/classes/CacheTest.php
Labels: dependencies, type:helper, type:major, type:modules, type:admin, type:tests, type:templates, theme:docs, type:build, patch, approved

#104 Develop
  install.php
  package.json
  postcss.config.js
  system/data/mysql_tables.php
  system/modules/Register.php
  tailwind.config.js
  templates/Mixchat/register/old.blade.php
  templates/Mixchat/register/step3.blade.php
Labels: type:modules, type:templates, approved
